//************************************************************************************************************
//
// © 2016-2019 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*************************************************************************************************************
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201603DA.asn"
 * 	`asn1c -fcompound-names -gen-PER -gen-OER -pdu=auto`
 */

#ifndef	_PartIIcontent_H_
#define	_PartIIcontent_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PartII-Id.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "VehicleSafetyExtensions.h"
#include "SpecialVehicleExtensions.h"
#include "SupplementalVehicleExtensions.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PartIIcontent_151P0__partII_Value_PR {
	PartIIcontent_151P0__partII_Value_PR_NOTHING,	/* No components present */
	PartIIcontent_151P0__partII_Value_PR_VehicleSafetyExtensions,
	PartIIcontent_151P0__partII_Value_PR_SpecialVehicleExtensions,
	PartIIcontent_151P0__partII_Value_PR_SupplementalVehicleExtensions
} PartIIcontent_151P0__partII_Value_PR;

/* PartIIcontent */
typedef struct PartIIcontent_151P0 {
	PartII_Id_t	 partII_Id;
	struct PartIIcontent_151P0__partII_Value {
		PartIIcontent_151P0__partII_Value_PR present;
		union PartIIcontent_151P0__partII_Value_u {
			VehicleSafetyExtensions_t	 VehicleSafetyExtensions;
			SpecialVehicleExtensions_t	 SpecialVehicleExtensions;
			SupplementalVehicleExtensions_t	 SupplementalVehicleExtensions;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} partII_Value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PartIIcontent_151P0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PartIIcontent_151P0;
extern asn_SEQUENCE_specifics_t asn_SPC_PartIIcontent_151P0_specs_1;
extern asn_TYPE_member_t asn_MBR_PartIIcontent_151P0_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PartIIcontent_H_ */
#include <asn_internal.h>
