//************************************************************************************************************
//
// © 2016-2019 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*************************************************************************************************************
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201603DA.asn"
 * 	`asn1c -fcompound-names -gen-PER -gen-OER -pdu=auto`
 */

#ifndef	_PreemptPriorityList_H_
#define	_PreemptPriorityList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SignalControlZone;

/* PreemptPriorityList */
typedef struct PreemptPriorityList {
	A_SEQUENCE_OF(struct SignalControlZone) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PreemptPriorityList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PreemptPriorityList;
extern asn_SET_OF_specifics_t asn_SPC_PreemptPriorityList_specs_1;
extern asn_TYPE_member_t asn_MBR_PreemptPriorityList_1[1];
extern asn_per_constraints_t asn_PER_type_PreemptPriorityList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SignalControlZone.h"

#endif	/* _PreemptPriorityList_H_ */
#include <asn_internal.h>
